### ISSUE TITLE
Proving non-inflation

### ISSUE THREAD

**Issue by chjj** [handshake-org/hs-airdrop#1]
Since we now have a magic merkle tree which conjures coins, we need to prove that the supply is finite.

Two ways to do this:

1. Make the entire tree a merkle sum tree. We will know that it can never conjure more value than the value attached to the root node.
2. Add a consensus rule that only X amount of value can ever exit the tree.

The second method doesn't prove the amount of value in the tree, it only guarantees non-inflation. They're both kind of annoying. The first one requires a bunch of new merkle code and makes the proofs bigger. The second requires some extra bookkeeping on-chain.

**Comment by rojii** [comment]
Which one of the two are you favoring? do you believe testing out both methods is the only way to be certain as to what is the most viable solution?

**Comment by chjj** [comment]
Update: the "faucet" tree is now separate from the airdrop tree. I've published all the leaf preimages for it in hs-tree-data. This should be sufficient to prove non-inflation as the airdrop tree has a constant value associated with each leaf.
