### ISSUE TITLE
Could not find nonce in bucket 30 - My account with 15 or more followers on 2019

### ISSUE THREAD

**Issue by liguobao** [handshake-org/hs-airdrop#102]
#35 

like issues 35, I also did not have a ssh key.
but My settings/keys show the ssh key add to Github is 
"Added on 12 Oct 2018" and "Added on 9 Jul 2018".

My account with 15 or more followers on 2019.

So?

**Comment by pinheadmz** [comment]
If your key is not in the airdrop tree you must not have qualified at the time of the airdrop. You can try others keys if you have any but there's nothing we can do.
