### ISSUE TITLE
claiming multiple airdrops in same block

### ISSUE THREAD

**Issue by freedomfighter2020** [handshake-org/hs-airdrop#109]
i claimed a total of 6 github airdrops for me and my coworkers
however i only received tokens for 5 of them
the issue seems to be with claiming more than 1 in the same block
https://hnscan.com/address/hs1qpkeldmswn4ju2rr3femmqhtly5tndn779hna5s

**Comment by pinheadmz** [comment]
What wallet are you using? You should open this issue in that repo, this is not a problem with hs-airdrop.

If you are using Bob, there is already a patch in place for this:

https://github.com/kyokan/bob-wallet/pull/105

Bob currently doesn't show the total amount received per TX if a TX has more than one output for the wallet. However, the total balance WILL reflect the correct amount.

I should also mention that we get so many reports about stolen github keys and github users being scammed out of their github keys or selling their keys, etc -- the fact that you in any way were able to personally obtain more than one key for the airdrop is worrisome. I trust that you are in fact working cooperatively with other airdrop recipients and that you are an honest person with honest interest in Handshake. Just beware that this is a red flag.

**Comment by boymanjor** [comment]
I think this is an issue with HNScan (cc: @kilpatty). A different block explorer reports the correct amount of coins: https://shakescan.com/address/hs1qpkeldmswn4ju2rr3femmqhtly5tndn779hna5s.

@freedomfighter2020 you should check the balance in your wallet. As @pinheadmz noted, this is not an issue with hs-airdrop. I am going to close this.

**Comment by kilpatty** [comment]
Not to muddy this issue, but have a fix coming for this in HNScan today!
