### ISSUE TITLE
out-of-bounds read on sendrawairdrop

### ISSUE THREAD

**Issue by smacke** [handshake-org/hs-airdrop#112]
`./bin/hsd-rpc sendrawairdrop $BASE64_STR`

results in:

`Out of bounds read (offset=969).`

**Comment by smacke** [comment]
This is on version 0.0.8 of hs-client.

**Comment by pinheadmz** [comment]
How did you create the raw airdrop base64 string?

**Comment by smacke** [comment]
I used the instructions [here](https://handshake.org/claim/), using the base64 output by this command:

`./bin/hs-airdrop ~/.ssh/id_rsa hs1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

**Comment by smacke** [comment]
hs-airdrop version 0.7.1

**Comment by pinheadmz** [comment]
And the latest version of hsd as well? Was there any more detail or stack trace in the log or hsd output when you ran `sendrawairdrop` ?

**Comment by smacke** [comment]
hsd version 2.1.5. I didn't see anything that jumped out at me in the logs, though admittedly I'm not familiar at all with what to look for.

If I run with loglevel "debug", I get the following messages in hsd:
```
[debug] (rpc) Handling RPC call: sendrawairdrop.
[debug] (rpc) [ 'base64_string_from_rpc_call_surrounded_in_squotes' ]
```

 There was a warning 'no reward address set up for miner', but I'm guessing that doesn't matter since I'm not mining. I haven't created a wallet using the steps [here](https://hsd-dev.org/guides/wallet.html) but I honestly don't know whether this is necessary. Overall, I have no idea what I'm doing -- think of me as a dumb monkey following instructions verbatim :)

**Comment by smacke** [comment]
I did a bit more investigation. This is happening inside of the file `bufio/lib/reader.js`, in the `check` method. Looks like a simple bounds check for a buffered reader. I can try and get a stack trace.

**Comment by pinheadmz** [comment]
Yeah, actually if you are ok with a bit of a privacy leak, you can send me your base64 string (its basically a raw transaction, already signed, and not malleable)

I can debug it and see if maybe you are using an unsual key type or something thats triggering a bug.

Feel free to email me directly if you like pinheadmz@gmail.com or you could just post here.

**Comment by smacke** [comment]
Eh, what the heck, I've already trusted `hs-airdrop` with my private key so why not. Here's my base64 string:

`zMEAABIsn4sjhewpkauprpPfyk6lOz0bL/P/YFpITkTlRUZwxGUz9UJVg233Mb1spVK2m2fEm+dRYNEbiH3c0VWWN05o91N4RyiFrZragms0vxYuo/VX9l5hUtc8M0NBwKQFEeZXdeXQR+3ev579hWeHa+1XBsdVwELTdHtt7Rd+sgqIRAtpyJbnJ3njDY22M0oPW72t0WAgcUL1+5/vhi8kFYdukLu5gdVAU5q8hBcrexsErjleiSb66MJ2kO4C/m8Pnr/lhA0z4JDSLndAHS8VxOuimAAB2//XxstMzD3K42RDN0ExdbUApqsm98LcPq0tQrXVaVD6+cSyu4UPpBsPU6USTJDMIywXTev5QCOzOPwS3xQku9d3DfiPvpxY6AR8JAEa4tAlOX1qdZ0BhGPCc4XFBneVPwpaXFEuKdB3n92j8cj0AZt8/EIHlREO6iU98JQtP+I5ptHh0B6/zWY0pZSgMb6MbxKYxVqilY2Eg7nG/fdiDT31yexvqNWlQa0kjtDIifSZrsLzEaU1poEjfs+1Um+MsjuMfG3KnEh/Fjs8dqmjO79obCuLAcRAKxKCBJjGPUcPfR/q2aYU5UgH72V8xZS28j0PS8GKjBXjbt1Xk/QAoX0BItMh27cO5C5rhrnHbR2NfFQ6cz7cc5vQEHkeY6Es71iBFf7N/DaEcLaKTIK64bcNrca9kKNQAb3yEoBfQHh0vB3Sp5QCNe4BRJuFO/ib69fyWOGaKBvVoSHo2Uri0xxnD3dSZVkPNJWl7DgDAzEddODzwgULnL9kiV4aV8S+ATykWKhRHw8AeRs7caYiGyvGrtgajJsuG7QV1BlQ/vE3w6RuH505cuURS9p/leRLwrInMIDK7eRa/sUOA3vRWnWlbuO3EpjfbRmv9eTVzv0BAQEzFdf5pWNO6pZi5BgYDGtsMjkzP88nilzXNmSwbLyEbJU9GiNkfqgHYFiTMWAtaXOtebVfLeAL6ddIvvejp3KiiWpINKBxqqWZ2/Vamhyn6QXHQnX8rS6OXiOUkEeYanwqYwfDE1OidVB17HououJoqmS1pRfAdK9kNHJnw00OtXgfeEJOjFP7HnEsD4j4u+991cFXOPsXfHTZrwYOrmfViWXro/CkqG+9fFwe8ATEKyYCT5BCzxzArnaWabLqSOtEG1buCt5vEfcMBuGx+JO8yPV8EKZcgZ2wioaMkhy3FC+qQQR356E+0Rmg99XnSGR2r7P1binWklmu6UilHqRzABSwiPFwI+1vWqNTADdrzNGrGRzdKP6ghgEA/awHUO8Uhf9EXt6ec5U0bcsjkfB9+C7S2oYvl4fUCiSeiTl3LzD4joeHIBigEW+6VP5gTNXCdBrKHzbXioRi92QWRwqeHp8Cnq2bfD19AmAGGa/EyY+IVThlHho/pr6EVS2iFT8Txwx8WQXh7A9QOc3kqapDgccxWs/WyAjn8vtFSpZRh32Tw79B7r+5nmiUREHRXSirnbiZDV2+EFnYlPecgZXVdmq/sbftNkZ4nbu0jxdBYx8uxCo4DLbZfoEw3oRNK7n3hYwW0mJJOiRi3pliJ0bfpuDuWY+KneIUB+iPfwymY4UOdTF2RUpPyzMsQVDWQfYlWc5YWrmNeJWTkml2Ux7xtyuCfvnH8uAjunfHW6s0RfQjX7S1EMTG8vtL96GkI7dEKW51u/ucO9Jhre/xH+2lbJKtFVDWX6n544SaSOR8WpTJlPqsW3nFols84kPOoVhYwzCGRJwnPN0ojgLMMx9WkEVSqE7G4MqqGVeCqSnGZeOZnRZeVmcuAkGU/+tdeRsOwPsOemC7gyjWowMJ+v63+CAIITDCO7lNSohPx6GNS447STK5oO4TMQ2mO8aGd4kQLUAOzNFjmTwKiFN7YIQjZ/lk2/Z49RYJTX0UZT37MNFr4scSFq/f9H1aIQrhtURUwr1eTfiJtWiRWPrqgvVZ+86Lp11u0612w/5VXEDcZvQ1yuF1MLcC+3CdeGSjta5pFokEN1yrMVqnsiteAG3v0KuHBdw+PNGd2b2qahC0zGSc7IchKp1lgRniblCdJztpaoRX+pojb1/EGR8t6kjZNpYmWnB830gSTKw5esW9C6e+SvyTCNfvu2neomLhyLEK2MDiFHbtL9gGuTWArzOt61FRYOn+Wrm/kHvKe2ytSHVGqJ6dgvp7ugG65k2bbNfTpjqNwQPHVdM7DbCocXolciRDqmZhORTl4T6PfQ+ton4YDyJsrOGnvaTEocr7tESegtTsYMT0qnffPgrxcFISe4ikOqqqv+XO55dsFAhE+5eju0W4WjAOqFK9CeeEy7DN0X+W/cvQIgRp9llFjorDyxVafpXWWGapuDj4Hd/xGU4qHu+oRpBrpN/RAc/MxxtYAFe547JITMRRz8sJ/Me0t8OTJCPgpEaCEO7xkWKktZ72R1tu6eiBp7x3XUUdoiPprM7x3SXF+Adn+UKl80IclKoGMI3c2FvA9/KM5qLJXJIrPYbuPUjNobJFuLGFoyZUNKIhqD1gVR07474XS3VKi3MlTsXJ2EqEcH1uUMbfzYjpfDL1qKsfLxMCSDsNgPy1tydGDa2dJbDKS7h7/CuX3hlquKMRWtKLGmE7PyzBHf3/XmFkuf/UEkI9m8HxkkVcpUqqP2sEyUywZLT6hFnrvqDXTCVid/ttm5L7fOth8P1VyXDIzSYO5JHdsLh+9hUI8jYB9NNcUVb+Ru0W1f4QsuJwY0brK3BHsheZWC6/Qhu8g8GRNaJj4TPPKCBLCgfM4WiDiSOA77YF6JW23hbKg5y3FdufMgIB/x3TMRTkJKygoNfxs1hPagemFW9waS1SEAvyDoFWUuTm5hRw+H5/kiKrjA3h2HS7z9EyPExlAHnFf9Q7MXOzYaERzrtxH0s4c99HEVI/9/j8i8kZ2fR9fpiRibMXLmltF5flrm7hM6gdqZCCTfca6Mx3D3jhz+398u+fKJESYbvnEK81D/nCfuWs2uIY3Bq/o4ZDxM3lL49sdNHXy1IzgNg+4JqUKZyqh71EcLyrnP4KW9XmOZcxSZNP6Y+rWZgu29lqR6gRWDXYc2aLtmn8t8n2SIgAcTvPR6xX8fuaznFMFHMtIfY5hT/958iJXi+pSCBjX3eMVKqBfTNA0xsRI64DjInH/yUKyXIlTksmmUJ34hMv+cbbppVRdjBqw22mmDZ47M4xKmSuln0GA/KuR20FkI7DhPivCk73hYqDCDfapZNcGlYLms1FfbvespF9XWDUlWKQAZlyGP/3cPSQbCfycxr89QqsCkv+a/5z9uNxhyzHz3jPbMAA/5ut8YavHL4chhCyme8aOdGF8hqBkiasH32kVK++mU8NaEJlJd2taoLFKEpSw3toGFNwBhfAXzL0TQi8kEAAAAAAAAAAAAAAAAAAAAAADnEVJwzOUBvrSEUK6ADtEdYiVtp7dI+/alEbCPjyosT5vABAiCOrV7g9lVCdmq9gMv0NRgjhM2Rej9zP1VyM2Kvlo55kI7ZGRki5Cw2lUvbm9IXtx6zttCPo9UdtioVJK/kTgVTQ8G9P91hW2/ofRCgZei0ETtDwKmIiyfacryH+svKFMSe35Yrv1RiaFUuZTMTTgLIw10W9DfB/G4YBhT4F6NO8XocQ4hxlFIV6YgMd+XanLq2piKT4VNCl9wJ8K9S2xutyUv+4CpK0XKlQ59buZdqUPd3qc3KwuDWByhuWvmnzGhQCo8kS66/x+jhqt8XqvMs6Ef+9vAalIrh3ydDxBaxQvNz+ngFL16XQsTlE3Xe+KKfidAThI3JF7LI7lDpk0IpP0qRkrDwFXuOEBk4IxEAnYDD9yMLtIPRt1grYM3q7pA8PvCMpRp2w50nxEI6o65ze/il1r1nQE66t4YcGt6VQlGB5TMH72xl7qYGBE0bbqNdewA=`

**Comment by smacke** [comment]
(Thanks for looking into this, by the way)

**Comment by pinheadmz** [comment]
@chjj 
Looks like an issue with a goosig signature.
I patched hsd to output the proof object up to the point of failure which is
`this.signature = br.readVarBytes();`

```
{
  index: 49612,
  proof: [
    '2c9f8b2385ec2991aba9ae93dfca4ea53b3d1b2ff3ff605a484e44e5454670c4',
    '6533f54255836df731bd6ca552b69b67c49be75160d11b887ddcd15596374e68',
    'f75378472885ad9ada826b34bf162ea3f557f65e6152d73c334341c0a40511e6',
    '5775e5d047eddebf9efd8567876bed5706c755c042d3747b6ded177eb20a8844',
    '0b69c896e72779e30d8db6334a0f5bbdadd160207142f5fb9fef862f2415876e',
    '90bbb981d540539abc84172b7b1b04ae395e8926fae8c27690ee02fe6f0f9ebf',
    'e5840d33e090d22e77401d2f15c4eba2980001dbffd7c6cb4ccc3dcae3644337',
    '413175b500a6ab26f7c2dc3ead2d42b5d56950faf9c4b2bb850fa41b0f53a512',
    '4c90cc232c174debf94023b338fc12df1424bbd7770df88fbe9c58e8047c2401',
    '1ae2d025397d6a759d018463c27385c50677953f0a5a5c512e29d0779fdda3f1',
    'c8f4019b7cfc420795110eea253df0942d3fe239a6d1e1d01ebfcd6634a594a0',
    '31be8c6f1298c55aa2958d8483b9c6fdf7620d3df5c9ec6fa8d5a541ad248ed0',
    'c889f499aec2f311a535a681237ecfb5526f8cb23b8c7c6dca9c487f163b3c76',
    'a9a33bbf686c2b8b01c4402b12820498c63d470f7d1fead9a614e54807ef657c',
    'c594b6f23d0f4bc18a8c15e36edd5793f400a17d0122d321dbb70ee42e6b86b9',
    'c76d1d8d7c543a733edc739bd010791e63a12cef588115fecdfc368470b68a4c',
    '82bae1b70dadc6bd90a35001bdf212805f407874bc1dd2a7940235ee01449b85',
    '3bf89bebd7f258e19a281bd5a121e8d94ae2d31c670f775265590f3495a5ec38'
  ],
  subindex: 3,
  subproof: [
    '311d74e0f3c2050b9cbf64895e1a57c4be013ca458a8511f0f00791b3b71a622',
    '1b2bc6aed81a8c9b2e1bb415d41950fef137c3a46e1f9d3972e5114bda7f95e4',
    '4bc2b2273080caede45afec50e037bd15a75a56ee3b71298df6d19aff5e4d5ce'
  ],
  key: {
    type: 'GOO',
    n: undefined,
    e: undefined,
    C1: '3315d7f9a5634eea9662e418180c6b6c3239333fcf278a5cd73664b06cbc846c953d1a23647ea80760589331602d6973ad79b55f2de00be9d748bef7a3a772a2896a4834a071aaa599dbf55a9a1ca7e905c74275fcad2e8e5e23949047986a7c2a6307c31353a2755075ec7a2ea2e268aa64b5a517c074af64347267c34d0eb5781f78424e8c53fb1e712c0f88f8bbef7dd5c15738fb177c74d9af060eae67d58965eba3f0a4a86fbd7c5c1ef004c42b26024f9042cf1cc0ae769669b2ea48eb441b56ee0ade6f11f70c06e1b1f893bcc8f57c10a65c819db08a868c921cb7142faa410477e7a13ed119a0f7d5e7486476afb3f56e29d69259aee948a51ea473',
    point: undefined,
    version: undefined,
    address: undefined,
    value: undefined,
    sponsor: undefined,
    nonce: undefined
  },
  version: 0,
  address: 'b088f17023ed6f5aa35300376bccd1ab191cdd28',
  fee: 100000,
  signature: ''
}
Thrown:
EncodingError: Out of bounds read (offset=969).
    at BufferReader.readBytes (/Users/matthewzipkin/Desktop/work/hsd/node_modules/bufio/lib/reader.js:606:10)
    at BufferReader.readVarBytes (/Users/matthewzipkin/Desktop/work/hsd/node_modules/bufio/lib/reader.js:630:17)
    at AirdropProof.read (/Users/matthewzipkin/Desktop/work/hsd/lib/primitives/airdropproof.js:167:25)
    at AirdropProof.decode (/Users/matthewzipkin/Desktop/work/hsd/lib/primitives/airdropproof.js:124:10)
    at AirdropProof.fromBase64 (/Users/matthewzipkin/Desktop/work/hsd/node_modules/bufio/lib/struct.js:123:17)
    at Function.fromBase64 (/Users/matthewzipkin/Desktop/work/hsd/node_modules/bufio/lib/struct.js:151:23) {
  type: 'EncodingError',
  name: 'EncodingError',
  code: 'ERR_ENCODING',
  message: 'Out of bounds read (offset=969).'
}
```

**Comment by pinheadmz** [comment]
@smacke you might be able to succeed by using the `--bare` option with `hs-airdrop` when you create your proof. If there is an issue with goosig, this will bypass it. It will identify your HNS coins with your actual public key but it may be this fancy crypto-blinding factor that is problematic.

**Comment by pinheadmz** [comment]
Also @smacke are you completely sure you're not missing any characters? This is 100% the exact output of the proof?

**Comment by smacke** [comment]
Unless something weird is going on with my copy+paste (possible given the number of tmux plugins I've installed), that should be the exact base64 representation of the proof.

Tried with `--bare` and got the same issue (slightly different offset).

**Comment by smacke** [comment]
Ugh, I'm really sorry for the waste of time... I'm getting different results depending on whether I paste the string directly into my terminal versus pasting it into a file `file.txt` and using the command `/bin/hsd-rpc sendrawairdrop $(cat file.txt)`. This is 100% a problem on my end, probably with some bizarro tmux or iterm2 config, really, really sorry for the false herring.

**Comment by smacke** [comment]
In case curious, somehow pasting directly in the terminal led to an extra 'f' at position 1455 in my base64 string. That's the only difference compared to when I paste into a file. Really, truly, bizarre.
