### ISSUE TITLE
Termux 

### ISSUE THREAD

**Issue by yasarsaiyad** [handshake-org/hs-airdrop#116]

**Comment by yasarsaiyad** [comment]
![IMG_20200628_113753_141](https://user-images.githubusercontent.com/52925333/85940197-9a85f980-b938-11ea-8a2b-68fe142f9bc1.jpg)



Having issue in the termux ...

**Comment by pinheadmz** [comment]
You need a C compiler to install the crypto library - I'm not surprised this doesn't work on Android. There might be a way to use the javascript fallback library instead but I would really not recommend this. For hs-airdrop you need your PGP key file as well to sign, is that possible on this platform?
