### ISSUE TITLE
I had to replace my ssh keys in April 2019, is it possible for me to claim?

### ISSUE THREAD

**Issue by balupton** [handshake-org/hs-airdrop#120]
I had to replace my ssh keys in April 2019, is it possible for me to claim? I don't seem to have access to the old ones, as never felt I needed to keep a copy.

**Comment by pinheadmz** [comment]
No, sorry, only the key from February 2019 is in the air drop tree and that is consensus critical, can not be changed.

**Comment by balupton** [comment]
Does my verified keybase gpg key include the airdrop for the github accounts?

**Comment by pinheadmz** [comment]
from the README:

> As a final addition, Hacker News accounts which are linked with Keybase accounts are included in the tree provided they were ~1.5 years old during the crawl.

This is the only keybase-related airdrop redemption protocol

**Comment by balupton** [comment]
So is there no association of which github account the ssh key is for?

**Comment by pinheadmz** [comment]
Not really, the airdrop does not know or care who you are, it just has a merkle tree of public keys and your key is either in that tree or no.

**Comment by balupton** [comment]
I have access to the GPG/PGP key used on github on feb 2019, can I use that?

**Comment by pinheadmz** [comment]
Wait, you have it? What's this mean then?

>  I don't seem to have access to the old ones, as never felt I needed to keep a copy.

From the README:

> The top ~250,000 users on github have had their SSH keys and PGP added to a merkle tree. Out of those ~250,000 users, ~175,000 of them had valid SSH and PGP keys at the time of tree creation.
> 
> If you had 15 or more followers on github during the week of 2019-02-04, your github SSH & PGP keys are included in the merkle tree.

**Comment by balupton** [comment]
> > I don't seem to have access to the old ones, as never felt I needed to keep a copy.

the ssh key

**Comment by pinheadmz** [comment]
Whatever key was on your github account in february 2019, there was a snapshot taken. It doesnt matter what else happened to your github account or the keys that were there AFTER the snapshot. If you still have the key, just try it!

**Comment by balupton** [comment]
ok thanks

I had the keybase gpg/pgp key succeed - which seems was linked to my github and hackernews at the time too

to confirm, what HNS amounts are typical for keybase only, and what HNS amounts are typical for github only?

So that I can compare what I received with what is expected (to make sure that I've been able to claim my airdrop for both hn and github)

**Comment by pinheadmz** [comment]
Nice! All airdrop amounts are around 4000 HNS I think. Keys were de-duplicated by email address so you may not be able to redeem more than one airdrop. And it's per key anyway - so if you had the same key on keybase and github, you dont get an extra airdrop just for having it in two places.

**Comment by balupton** [comment]
ah ok, that makes sense then, yeah that is about what I got

so even if I had different keys on github and keybase, the email deduplication would have prevented double-dipping?

**Comment by pinheadmz** [comment]
Yes, even if you had 10 keys on github, you should only get one airdrop. The keys are in sub-trees in the main airdrop tree.

**Comment by balupton** [comment]
Cool. For those interested, here was my steps:

1. Go to the keybase website, go to your own profile, click "edit" next to your gpg key, click "export my private key from Keybase", save as `keybase.pgp`
2. import into your local keyring: `gpg --import keybase.pgp`
3. get the longform key id: `gpg --keyid-format LONG -K`
    ```
    sec   rsa4096/SHORTFORMKEYID 2016-03-15 [SC]
      THELONGFORMKEYID
    ```
4. export into the format the app expects: `gpg --output keybase.asc --armor --export-secret-key THELONGFORMKEYID`
5. follow the instructions at https://www.namebase.io/airdrop using their wallet id: `./bin/hs-airdrop keybase.asc THELONGFORMKEYID WALLETID`
