### ISSUE TITLE
@pinheadmz how to solve this problem?

### ISSUE THREAD

**Issue by linnbenton** [handshake-org/hs-airdrop#121]
![Screenshot_48](https://user-images.githubusercontent.com/35951722/92316645-6d815180-f021-11ea-938a-ba42520fd00c.png)
after replacing a public key with a private key, then like that screenshot @pinheadmz how to solve this problem?

_Originally posted by @linnbenton in https://github.com/handshake-org/hs-airdrop/issues/61#issuecomment-687688414_

**Comment by pinheadmz** [comment]
"this means your key was not found in the airdrop tree"
This is not an issue with hs-airdrop

**Comment by linnbenton** [comment]
what is your solution so that my key is found in the airdrop tree? @pinheadmz 🆘
