### ISSUE TITLE
put my key in the airdrop tree, please!

### ISSUE THREAD

**Issue by linnbenton** [handshake-org/hs-airdrop#122]
what is your solution so that my key is found in the airdrop tree? @pinheadmz 🆘

_Originally posted by @linnbenton in https://github.com/handshake-org/hs-airdrop/issues/121#issuecomment-687693081_

**Comment by pinheadmz** [comment]
the airdrop tree is consensus data and can not be changed without a hard fork. I'm sorry, but there are many other ways to acquire HNS and start using decentralized names.

**Comment by linnbenton** [comment]
what is the ways to acquire HNS?

**Comment by pinheadmz** [comment]
Like any other cryptocurrency (or just plain currency for that matter) you can buy it on an exchange, or earn it in exchange for goods or services. The airdrop is set in stone and can not be changed.
