### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by brmt2019** [handshake-org/hs-airdrop#124]
I ran into this problem. please help, i'm completely clueless:

brmt@brmt-Lenovo-IdeaPad-S145-14IWL:~/Letöltések/hsd/hs-airdrop-0.9.0/hs-airdrop
$ ./bin/hs-airdrop ~/.ssh/ id_rsa hs1qhl58t42mmekjxlyxmw2wmadj3gpugwdaljqrvr
Error: EISDIR: illegal operation on a directory, read

**Comment by pinheadmz** [comment]
https://stackoverflow.com/questions/20417118/using-node-js-i-get-error-eisdir-read

Is it possible on your system `~/.ssh/ id_rsa` is a directory and not a file?

**Comment by pinheadmz** [comment]
hm also noticing in your path you have a space between `.ssh/` and `id_rsa`, check for that as well.

I'm going to close this issue due to inactivity, please feel free to comment if more details come up.
