### ISSUE TITLE
NonceError despite correct GitHub SSH key and > 15 followers

### ISSUE THREAD

**Issue by hubert3** [handshake-org/hs-airdrop#137]
Hi,

like a few other commenters here, hs-airdrop is telling me:

`NonceError: Could not find nonce in bucket xxx`

I am trying with an SSH key that I am confident was in place on my @hubert3 GitHub account in Feb 2019, and I definitely had > 15 followers at that time.

Are there any logs from when the GitHub data collection was done that can confirm whether my account was or wasn't included?

How were accounts with multiple SSH keys handled? Was the first public key shown on https://github.com/username.keys chosen?

The fingerprint of the old key I've retrieved from a backup matches with the Github SSH key add notification email dated 2016 and it's a 2048 bit RSA key. The next SSH key change notification email wasn't til 2020 and I tried that key too, so it ought to be the 2016 key.

If my account wasn't included in the airdrop for whatever reason that's fine, but it would be nice to know if it was selected before spending any more time on this (took me a while to find the right backup disk containing the 2016 key).

**Comment by pinheadmz** [comment]
> How were accounts with multiple SSH keys handled? Was the first public key shown on https://github.com/username.keys chosen?

All keys from your github account are in the airdrop tree, and all may qualify. However, each user is only to claim their airdrop once. This is handled with "subtrees" of keys for each user account, then the root of each subtree is the hash included (and proven) in the consensus airdrop merkle tree. If you had other keys on your account at the time of the snapshot, you should try those.

closing as duplicate: https://github.com/handshake-org/hs-airdrop/issues/35
