### ISSUE TITLE
Use Public Key to Determine Inclusion for Github Airdrop

### ISSUE THREAD

**Issue by tynes** [handshake-org/hs-airdrop#14]
Is it possible to do this? It would be really bad for privacy, but some users want to be certain that they are included in the airdrop before they are willing to share their private key with the software.

Is it possible that a user could sign a piece of data to determine if they are in the airdrop?

If we had the exact day that the tree data was collected, it would be a lot easier to explain to people

**Comment by mathstuf** [comment]
Agreed. Any chance of getting this support? @chjj

**Comment by pinheadmz** [comment]
@mathstuf you should be able to test an airdrop claim on regtest, on an offline machine (if you're worried). https://github.com/handshake-org/hs-airdrop

**Comment by mathstuf** [comment]
"regtest"? Also the docs are a bit unclear. I'll file a new issue for where things seem unclear to me.

**Comment by tynes** [comment]
If this was possible, it would be possible to brute for the entire set of participants in the airdrop by testing every key on Github. Privacy vs UX, classic tradeoff.

**Comment by boymanjor** [comment]
@tynes can we close this now?
