### ISSUE TITLE
Claim airdrop, accidentally erased the .hsw directory, any ways to recover?

### ISSUE THREAD

**Issue by din** [handshake-org/hs-airdrop#141]
Just claimed airdrop and then next thing I did is accidentally erased the .hsw directory. Didn't save the mnemonic, and I assume this is the only way to recover the wallet right? I have my terminal output with some tokens still in the terminal window. Am I out of luck with this? Is it possible to restore access without the mnemonic? Apologies I'm pretty new to all crypto-currency things.

**Comment by pinheadmz** [comment]
Welcome to Handshake, and cryptocurrency -- unfortunately small mistakes can be big mistakes when we expect users to take care of private keys. But let's not loose hope yet. First of all -- which guide did you follow? The reason I ask is that `hsd` does not create a `.hsw` directory by default -- in fact if you still have `~/.hsd/wallet` you may in good shape.

**Comment by din** [comment]
Thanks! I erased the whole `~/.hsw` directory and then after I ran `hsw-cli` it showed different information and didn't show previous account balance unfortunately. :( I followed the guide on http://handshake.org/claim/ and it was successful... until I have done the biggest mistake I suppose.

**Comment by pinheadmz** [comment]
Hm, doesn't sound great. I'm still curious about the `.hsw` directory - the guide doesn't mention creating it, are you sure there was such a directory? Perhaps you mean `.hsd` which, if you deleted without backing up and can not recover with your operating system tools, may indeed mean that your airdrop is lost. If that's the case we can offer you some bounties for contributions to code and documentation if you are still interested in getting involved!

**Comment by din** [comment]
Oh yeah, sorry about this. My mistake! The directory name is indeed `.hsd`. I might try to recover it later on but I think it is already gone. 

For the code contributions, I'm afraid I have very little knowledge in terms of contributing to cryptocurrency codebase, only maybe if you eventually have iOS/macOS clients for something, I could contribute to those.

Anyway thank you for the response! Next time something like this happens I will be more careful—lesson learned! 🤯
