### ISSUE TITLE
A better mechanism for finding interested and deserving open source developers.

### ISSUE THREAD

**Issue by Centuriondan** [handshake-org/hs-airdrop#15]
My biggest issue with this air drop is that it will probably miss many if not most deserving open source contributors, and may capture many that are not open source friendly at all.

I haven't yet figured out a better solution, but will update this ticket with ideas once I've had opportunity to give it some more thought.

At a minimum we'd need to define what is meant by "open source", "developers" for a start and then use those definitions to select worthy projects whose contributors might like an opportunity to benefit from the airdrop.

**Comment by tynes** [comment]
Its definitely not an easy problem to solve. One of the larger issues is sybil resistance, people will always try to figure out a way to cheat the system to get multiple airdrops

**Comment by filips123** [comment]
I think that it is not good to only have followers as the count for the airdrop. Users could have followers even if they aren't contributing to open source projects.

Instead, users for the airdrop should be determined by commits and pull requests submitted to open source repositories.

**Comment by boymanjor** [comment]
The airdrop is live on mainnet. I'm closing this now.
