### ISSUE TITLE
Who can give me some coins? My GitHub account was registered late

### ISSUE THREAD

**Issue by rdp-studio** [handshake-org/hs-airdrop#151]
Who can give me some coins? My GitHub account was registered late

**Comment by ibracadabra022** [comment]
I want

**Comment by pinheadmz** [comment]
@rdp-studio @ibracadabra022 github is a really bad place to beg for money. Do it again and I'll have to ban you from the organization.

**Comment by Emmyforeigncyher** [comment]
#149
