### ISSUE TITLE
Doubt regarding airdrop 

### ISSUE THREAD

**Issue by Shashi456** [handshake-org/hs-airdrop#16]
What if i did not have 15 followers during the said week.
> If you had 15 or more followers on github during the week of 2018-08-27, your github SSH & PGP keys are included in the merkle tree

Is this airdrop still on for users more than 15 followers?

**Comment by tynes** [comment]
The airdrop is still on for Github users who had more than 15 followers during the week of 2018-08-27

**Comment by adamhackbarth** [comment]
That counts me out. Thanks for the reminder.

**Comment by markbosky** [comment]
Does inclusion require that a qualified account contained both an SSH Key and GPG Key as of 2018-08-27? Am I understanding that if the account only had an associated SSH key, but no GPG key, then redemption isn't an option?

**Comment by boymanjor** [comment]
@markbosky you only need to have one or the other. I am going to close this issue for now.
