### ISSUE TITLE
Usage examples depict testnet addresses, but all faucet addresses are mainnet.

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hs-airdrop#19]
https://github.com/handshake-org/hs-airdrop#usage

I was trying to help an airdrop recipient on IRC manage the `faucet-tool` and generate an address. They were confused because they thought they would need to import their faucet-tool mnemonic seed into an hsd testnet full node wallet.

I tried to test airdrops on testnet with my own faucet address, but wasn't able to succeed. (Started by converting my mainnet faucet address to testnet, and commenting-out assertions until a proof was generated). Would be nice to be able to test faucet airdrop proofs on testnet, even after mainnet launches.

**Comment by boymanjor** [comment]
@pinheadmz can we close this now?

**Comment by pinheadmz** [comment]
Nice.
