### ISSUE TITLE
Multiple duplicate addresses in faucet tree, only first instance will be returned by findProofEntry()

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hs-airdrop#20]
I noticed a few addresses were duplicated in https://github.com/handshake-org/hs-tree-data/blob/master/proof.json and wrote a quick script to find them all (output below). One address is in the tree 62 times!

I'm not sure what caused this, if it's intended or not. Either way, the `hs-airdrop <addr>` script will only return a proof for the first occurrence of a given address:

https://github.com/handshake-org/hs-airdrop/blob/e92f14d00a27aa250d120b4d32786fea5dfc23b2/bin/hs-airdrop#L241-L246

So I'm sure with a little modification, that script could output proofs for EVERY instance of an address in the tree., but I'm not sure that's intended behavior. @chjj mentioned the tree will [likely be rebuilt once more before mainnet](https://github.com/handshake-org/hsd/issues/245#issuecomment-526677619) so maybe these dupes could be fixed during that process.

```
Map {
  'hs1qng3mfk23uuqynl8s287h6nul8pye2rajdvz2gu' => 2,
  'hs1qfnfj7p2qw3u2hgtl8mgg5whjcu3235yvqc4l47' => 62,
  'hs1q9drsmaqkpp7ewv4wedufw6rjgdcp9zv4e6c8le' => 2,
  'hs1qvvnv5h7tx96eg7pud3r3uzzwycyfsqmr5mm579' => 2,
  'hs1qnvkypvp5uchnujj8awl8th0lm998m0c7c3pf5y' => 2,
  'hs1qdj2xqy3rykp0n2kywzt8x77dr3fw0evmyrkz0j' => 2,
  'hs1qhsmch5g5dy9774ek46zmwk0pmj3z5ahrgsu0ep' => 2,
  'hs1qp99ll9m9rqk39w6lexh06mvevf9gnkm0tpt04f' => 2,
  'hs1qcjdr858rupg6lsfwenvg29d5mu3u967kywscg4' => 2,
  'hs1qhzvr94u7yanswn6et25nrje3fsucgsd5nhmqfg' => 2,
  'hs1qv7cndn4zttf2cyzw5dr330xnzylp5dz9dzh56x' => 2,
  'hs1qjk8ys3n3l7ct9lmpqsszxr34dn5h8efexfxf2j' => 2,
  'hs1q3lkysn74p39xfxc2pzf8ewmvaezwagsvehdd7t' => 2,
  'hs1qgfzuxpg05t4zs323ly3dtnuwpc9tt94glvkvxm' => 2,
  'hs1q58r3mr3lrxhzlrdyyvamyffg37a2vkasjlk9f8' => 2,
  'hs1qfnn556v4f5vcrvmmahh6ugt394k08wr22dnkxx' => 2,
  'hs1qymue45suswzt3ynkjl6vkutrafgfqr6g3dwzuc' => 2,
  'hs1qwrrlczge2vt0xa3ktwvfwdpchhftzc0zhwyvr3' => 2,
  'hs1qeh4q4el90mklmdjxxrd5rfk9j72c755gq69w8f' => 2,
  'hs1qylgr5j47v0slddupewgn0kgajm09qm9xpxxsc8' => 2,
  'hs1qxgwd3t6kzw72m4ywx4fj9rqx5fqqsa6fm2sltc' => 2,
  'hs1qygj6y7jcjam9s6nr3ds82ksg9wd7jqtu4csf3d' => 2 }
```

**Comment by chjj** [comment]
Interesting. I'm looking through my build scripts & data right now. It looks like someone may have sybil'd the faucet when it was still running. We'd probably have to ask Hans for more details.

**Comment by pinheadmz** [comment]
@hschoenburg ?

**Comment by chjj** [comment]
The build script now removes all duplicates. Closing.
