### ISSUE TITLE
"Could not find nonce in bucket" is not a clear error message

### ISSUE THREAD

**Issue by jacobhaven** [handshake-org/hs-airdrop#21]
Whenever a user attempts to generate a proof with a key that not in the tree is the tree, they get a rather confusing ["Could not find nonce in bucket ${bucket}."](https://github.com/handshake-org/hs-airdrop/blob/master/bin/hs-airdrop#L234) error.

This is a fairly common occurrence and users are usually confused by it. A better message would  explain that the key they're using is not eligible for an airdrop claim.

**Comment by pinheadmz** [comment]
Agreed. Have explained this error message 3 times in a week! 

https://old.reddit.com/r/handshake/comments/d3few3/having_trouble_claiming_tokens_with_the_airdrop/

**Comment by jacobhaven** [comment]
@pinheadmz This _only_ occurs for ineligible keys, right? (though it doesn't directly indicate whether a key is eligible because a claim could already have been mined)

I think maybe `Chosen key is not eligible for airdrop: could not find nonce in bucket ${bucket}.`.

It would be _nice_ if we caught the error in `main` and could say `Key with filename ${file} [...]`, but that's not super necessary.

**Comment by pinheadmz** [comment]
`hs-airdrop` won't know if a claim ha already been mined - its an off-chain tool that generates a proof. That proof gets transmitted to the chain, and double-spends are rejected at that point. That will include a github user with multiple keys, trying to claim from multiple keys.

"Eligible" is an unfortunate term too, I dunno. I think maybe

`Could not find public key in airdrop tree (nonce missing in bucket ${n}`

**Comment by jacobhaven** [comment]
Yeah, there are false negatives, but those people don't see a confusing error message here. They just get a (valid) proof that gets rejected 🤷‍♀.

I think "eligible" is a bit clearer. There _are_ eligibility requirements for a key to be in the tree, and the one they are are trying to use doesn't match them.

But, if you want to obfuscate that point a bit: `Chosen key is not in the airdrop tree` if more definitive. `Could not find` sounds like the `hs-airdrop` just didn't look hard enough, and it might work if you try something else or ask in a support forum. 😄
