### ISSUE TITLE
How to get seed phrase for import?

### ISSUE THREAD

**Issue by stephen304** [handshake-org/hs-airdrop#27]
Namebase has an import tab that says "If you went through the developer faucet on Handshake.org and received a seed phrase, you can paste that here to import your funds into your Namebase account."

Handshake.org links to this repo to claim HNS, but the docs here don't seem to show how to get the seed phrase. I want to avoid running a full node since I just want to buy domains. Ideally I would like to take the airdrop and transfer it directly to namebase. It seems the current example requires running a full hsd node to complete the claim.

The reason why I want to avoid running a full node is honestly because I don't want to wade through documentation to set it up so I can claim just so I can transfer it all out again. Currently trying to run hsd results in `Mainnet genesis block must be generated.`, and if I can bypass this intermediate step that would make things much easier.

Edit: So I made some progress using these steps
* The arch hsd-git pkgbuild builds hsd without `--production`, so I added that to the end of the `npm install` line, this *seemed* to fix the genesis block issue letting me run hsd as my normal user with `hsd`
* I then cloned and built hs-airdrop and hs-client, and created the airdrop proof with `./bin/hs-airdrop ~/.ssh/id_rsa <wallet_address>`. This gave me the error:

```
Downloading: https://github.com/handshake-org/hs-tree-data/raw/master/tree.bin...
Error: Response exceeded limit.
    at Request.handleResponse (/home/stephen/git/stephen304.com/hs-airdrop/node_modules/brq/lib/request.js:508:19)
    at ClientRequest.emit (events.js:321:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:602:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:471:22)
    at TLSSocket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```
* I resolved this error by manually downloading `https://github.com/handshake-org/hs-tree-data/raw/master/tree.bin` and placing it in the proper location `mv ~/Downloads/tree.bin ~/.hs-tree-data`
* Running the airdrop command again successfully created the proof.
* I am a little disappointed that I can't seem to find the amount that the proof is good for - which makes it hard to evaluate whether the default fee amount is a significant portion of the airdrop amount

**Comment by boymanjor** [comment]
>I am a little disappointed that I can't seem to find the amount that the proof is good for - which makes it hard to evaluate whether the default fee amount is a significant portion of the airdrop amount

@stephen304 the airdrop proof is worth [`4,246,994,314`](https://github.com/handshake-org/hs-airdrop/blob/master/etc/tree.json#L11) dollarydoos, i.e. `4246.994314` HNS.

**Comment by stephen304** [comment]
Thanks @boymanjor , do you know how to check the status of the airdrop after submitting? I created the proof with my namebase wallet address and submitted it this morning but nothing has come through, creating additional proofs and submitting seems to error so I'm guessing it went through but I don't know what to expect for availability of funds. I'd like the ability to participate in the next week of auctions.

**Comment by pinheadmz** [comment]
Miners are overloaded with airdrop proofs right now. They only include 10 per block, and the sponsor proofs pay fees of 100-500 HNS each! So it may take several hours to mine yours. If you have an "urgent" need for HNS, you could try including a fee > 100 HNS and rebroadcasting.

**Comment by pinheadmz** [comment]
Unclear documentation closed by https://github.com/handshake-org/hs-airdrop/commit/cd90f42cf806dc4c037b03db5548cd14e3a5852a

- amount of airdrop
- hint about deleting hs-tree-data

@stephen304 feel free to add more comments if you have other issues, or reach out to us on IRC

**Comment by stephen304** [comment]
@pinheadmz Was the `Response exceeded limit` error fixed? That was the most confusing roadblock I hit when trying to use it. Also it would be good to mention how much the default fee is.

**Comment by pinheadmz** [comment]
@stephen304 can you check you have the latest version of `hs-airdrop`?

Specifically check this line:

https://github.com/handshake-org/hs-airdrop/blob/ccc42fe7c29d465d0eef51bd0f3e2f49946cdc15/bin/hs-airdrop#L127

**Comment by stephen304** [comment]
@pinheadmz Ah, looks like boymanjor fixed it a few days after I created this ticket.
