### ISSUE TITLE
Issue claiming

### ISSUE THREAD

**Issue by josescasanova** [handshake-org/hs-airdrop#34]
Hey everyone, I'm having an issue claiming the airdrop tokens and looking for some guidance. These are the steps that I've taken:

- I checked and verified my HNS wallet address is in https://github.com/handshake-org/hs-tree-data/blob/master/proof.json . I also have the initial seed phrase from when I created it.
- Cloned + installed `hs-airdrop`
- Ran `./hs-airdrop ~/.ssh/id_rsa <WALLET_REDACTED> -f 0.5`

This is where the trouble happens. I reformatted my computer about 4 months ago, but backed up my ssh keys. I also reset my GH ssh to a new one upon reformatting. I've tried verifying myself with the backed up ssh keys along with my current one with no avail.

Is there a step that I'm missing or is there another way to verify? Thank you

**Comment by boymanjor** [comment]
@josescasanova if your address is in [hs-tree-data](https://github.com/handshake-org/hs-tree-data/blob/master/proof.json), then it was removed from the airdrop tree, i.e. you do not need to use your ssh key to claim. You can claim by running:
```js
$ hs-airdrop [addr]
```

**Comment by josescasanova** [comment]
> @josescasanova if your address is in [hs-tree-data](https://github.com/handshake-org/hs-tree-data/blob/master/proof.json), then it was removed from the airdrop tree, i.e. you do not need to use your ssh key to claim. You can claim by running:
> 
> ```js
> $ hs-airdrop [addr]
> ```

My original address shows the tokens there now! Thank you @boymanjor !!
