### ISSUE TITLE
It seem that the service of 151.101.22.133:433 didn't work ？

### ISSUE THREAD

**Issue by daijiale** [handshake-org/hs-airdrop#37]
When I run ' ./bin/hs-airdrop ~/.ssh/id_rsa  address fee '  in my shell ：

What 's the passphrase I should input ? 

And then the log is :

> Attempting to create proof.
> This may take a bit.
> Decrypting nonce...
> Downloading: https://github.com/handshake-org/hs-tree-data/raw/master/nonces/093.bin...
> Error: connect ECONNREFUSED 151.101.228.133:443
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
> 

It seem that the service of 151.101.22.133:433 didn't work ？  How to fix it？

**Comment by imcda** [comment]
same problem

**Comment by imcda** [comment]
> When I run ' ./bin/hs-airdrop ~/.ssh/id_rsa address fee ' in my shell ：
> 
> What 's the passphrase I should input ?
> 
> And then the log is :
> 
> > Attempting to create proof.
> > This may take a bit.
> > Decrypting nonce...
> > Downloading: https://github.com/handshake-org/hs-tree-data/raw/master/nonces/093.bin...
> > Error: connect ECONNREFUSED 151.101.228.133:443
> > at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
> 
> It seem that the service of 151.101.22.133:433 didn't work ？ How to fix it？

did you use the VPN in terminal？PS. global-mode.

**Comment by daijiale** [comment]
> > When I run ' ./bin/hs-airdrop ~/.ssh/id_rsa address fee ' in my shell ：
> > What 's the passphrase I should input ?
> > And then the log is :
> > > Attempting to create proof.
> > > This may take a bit.
> > > Decrypting nonce...
> > > Downloading: https://github.com/handshake-org/hs-tree-data/raw/master/nonces/093.bin...
> > > Error: connect ECONNREFUSED 151.101.228.133:443
> > > at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
> > 
> > 
> > It seem that the service of 151.101.22.133:433 didn't work ？ How to fix it？
> 
> did you use the VPN in terminal？PS. global-mode.
 
I try VPN and export http_proxy in terminal ! Didn't work as well ,  Had you fixed it ?

**Comment by pinheadmz** [comment]
The password is for the private key you passed to the tool. The key needs to be decrypted so the tool can sign a message with it.

For everyone getting network errors, I'm not sure but it could just be that GitHub is sluggish or maybe everyones trying to claim all at once.

You can also just clone https://github.com/handshake-org/hs-tree-data and save it as `~/.hs-tree-data` in your home directory. the hs-airdrop tool looks there for the tree data before attempting to download

**Comment by imcda** [comment]
> > > When I run ' ./bin/hs-airdrop ~/.ssh/id_rsa address fee ' in my shell ：
> > > What 's the passphrase I should input ?
> > > And then the log is :
> > > > Attempting to create proof.
> > > > This may take a bit.
> > > > Decrypting nonce...
> > > > Downloading: https://github.com/handshake-org/hs-tree-data/raw/master/nonces/093.bin...
> > > > Error: connect ECONNREFUSED 151.101.228.133:443
> > > > at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
> > > 
> > > 
> > > It seem that the service of 151.101.22.133:433 didn't work ？ How to fix it？
> > 
> > 
> > did you use the VPN in terminal？PS. global-mode.
> 
> I try VPN and export http_proxy in terminal ! Didn't work as well , Had you fixed it ?

Recommend Proxifier, that's real global-mode for your terminal. try-try-look.:)

**Comment by daijiale** [comment]
> The password is for the private key you passed to the tool. The key needs to be decrypted so the tool can sign a message with it.
> 
> For everyone getting network errors, I'm not sure but it could just be that GitHub is sluggish or maybe everyones trying to claim all at once.
> 
> You can also just clone https://github.com/handshake-org/hs-tree-data and save it as `~/.hs-tree-data` in your home directory. the hs-airdrop tool looks there for the tree data before attempting to download

Thanks ~ It works , but I meet a new problem the same as the issue : [https://github.com/handshake-org/hs-airdrop/issues/35](url)

**Comment by imcda** [comment]
> > The password is for the private key you passed to the tool. The key needs to be decrypted so the tool can sign a message with it.
> > For everyone getting network errors, I'm not sure but it could just be that GitHub is sluggish or maybe everyones trying to claim all at once.
> > You can also just clone https://github.com/handshake-org/hs-tree-data and save it as `~/.hs-tree-data` in your home directory. the hs-airdrop tool looks there for the tree data before attempting to download
> 
> Thanks ~ It works , but I meet a new problem the same as the issue : #35

I also got this message, I think that means we didn't meet the requirements, I am not sure.GIVE UP the airdrop, lol.

**Comment by boymanjor** [comment]
@imcda @daijiale yes, that message means your key was not included in the airdrop. I am closing this issue for now.
