### ISSUE TITLE
Error: Invalid checksum: tree.bin

### ISSUE THREAD

**Issue by qiushaoxi** [handshake-org/hs-airdrop#38]
Decrypting nonce...
Found nonce!
Rebuilding tree...
Downloading: https://github.com/handshake-org/hs-tree-data/raw/master/tree.bin...

Error: Invalid checksum: tree.bin

**Comment by pinheadmz** [comment]
Check if you have old data, remove and reinstall everything:

https://github.com/handshake-org/hs-airdrop#notes

**Comment by FrankFang** [comment]
How did you solve it?

**Comment by pinheadmz** [comment]
@FrankFang https://github.com/handshake-org/hs-airdrop/issues/38#issuecomment-586728569
