### ISSUE TITLE
Still on "Airdrop: waiting for more confirmations" after 24h

### ISSUE THREAD

**Issue by leeduckgo** [handshake-org/hs-airdrop#41]
as pic below
![image](https://user-images.githubusercontent.com/12784118/74705797-13b96580-5250-11ea-992d-566049f48983.png)

**Comment by leeduckgo** [comment]
the fee is 0.01 as recommendation.

**Comment by leeduckgo** [comment]
Got It, thx !

**Comment by liudongmiao** [comment]
https://github.com/handshake-org/hs-airdrop/issues/41#issue-566650943

**Comment by pradumangoyal** [comment]
@leeduckgo, What was that? I am getting the same.

**Comment by leeduckgo** [comment]
> @leeduckgo, What was that? I am getting the same.

Just wait for more hours.

**Comment by pinheadmz** [comment]
Please contact Namebase support for issues related to Namebase. This is not Namebase support and so I am going to lock this thread.
