### ISSUE TITLE
key was not found

### ISSUE THREAD

**Issue by fairchild88** [handshake-org/hs-airdrop#42]
when I execute 
   
     ./bin/hs-airdrop ~/.ssh/id_rsa_github [addr] 0.010

I got follow error response 

    Attempting to create proof.
    This may take a bit.
    Decrypting nonce...
    NonceError: Could not find nonce in bucket 58.
        at findNonces (/Users/Fei/AndroidStudioProjects/hs-airdrop/bin/hs-airdrop:275:17)
        at async createKeyProofs (/Users/Fei/AndroidStudioProjects/hs-airdrop/bin/hs-airdrop:328:17)
        at async main (/Users/Fei/AndroidStudioProjects/hs-airdrop/bin/hs-airdrop:746:8)

    This means your key was not found in the airdrop tree.

My github ssh key was added at 3 April 2019. Have that been added to bucket or do I have any method to add it to bucket again?  :-)

**Comment by boymanjor** [comment]
@fairchild88 your key was not included in the airdrop tree. The final snapshot of the tree was created in Feb. 2019. I'm sorry, there is nothing we can do to retroactively add you to the airdrop.

**Comment by Nakilon** [comment]
Does this mean if my private key was generated on 23 Sep 2019 I can't claim by HNS?!
