### ISSUE TITLE
errors.claimNot NamebaseAddr

### ISSUE THREAD

**Issue by ucfyao** [handshake-org/hs-airdrop#50]
when submit the base64 code,tips:errors.claimNotNamebaseAddr

**Comment by pinheadmz** [comment]
This is not Namebase customer support.

**Comment by ucfyao** [comment]
![image](https://user-images.githubusercontent.com/11612671/74897093-f65fd500-53d0-11ea-9a95-68fa87cb1448.png)

**Comment by ucfyao** [comment]
Who can solve this problem？

**Comment by pinheadmz** [comment]
This is not Namebase customer support!

**Comment by Lmy0217** [comment]
@ucfyao I use lastest wallet address and fix this problem.
