### ISSUE TITLE
Error: TypeError: stdin.setRawMode is not a function

### ISSUE THREAD

**Issue by pjmike** [handshake-org/hs-airdrop#51]
Hi, when I run the command:  `./bin/hs-airdrop <path to key> <address> <fee>`  ，it give me the error: 

TypeError: stdin.setRawMode is not a function
    at readLine (F:\hs-airdrop\lib\readline.js:17:9)
    at readPassphrase (F:\hs-airdrop\lib\readline.js:92:10)
    at readKey (F:\hs-airdrop\bin\hs-airdrop:535:32)

**Comment by pinheadmz** [comment]
What operating system?
What version of nodejs?

**Comment by pinheadmz** [comment]
Is this relevant?

https://github.com/workshopper/stream-adventure/issues/171#issuecomment-202203709

**Comment by pjmike** [comment]
> What operating system?
> What version of nodejs?

**system**: window 10
**node**: v10.15.0
**npm**: v6.4.1
**Command line tool**:  git bash

**Comment by wobiancao** [comment]
me too.

**Comment by elunez** [comment]
> What operating system?
> What version of nodejs?

me too.

```
system: window 10
node: v12.13.1
npm: 6.12.1
Command line tool: git bash
```
![image](https://user-images.githubusercontent.com/42142420/74936861-deff0700-5425-11ea-9077-2d8450d7b830.png)

**Comment by tuxcanfly** [comment]
Can you try `node bin/hs-airdrop <path to key> <address> <fee>` ?

**Comment by elunez** [comment]
> Can you try `node bin/hs-airdrop <path to key> <address> <fee>` ?

it still gives an error：
```
λ node /bin/hs-airdrop ~/.ssh/id_rsa ***** 0.01         
internal/modules/cjs/loader.js:800                                                           
    throw err;                                                                               
    ^                                                                                        
                                                                                             
Error: Cannot find module 'E:\bin\hs-airdrop'                                                
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)              
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)                         
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)                      
    at internal/main/run_main_module.js:17:11 {                                              
  code: 'MODULE_NOT_FOUND',                                                                  
  requireStack: []                                                                           
}                                                                                            
                                                                                             
```

**Comment by tuxcanfly** [comment]
You need to do this from within the `hs-airdrop` directory.

**Comment by wobiancao** [comment]
> Can you try `node bin/hs-airdrop <path to key> <address> <fee>` ?

good .

but my key not in airdrop...sad

**Comment by elunez** [comment]
> You need to do this from within the `hs-airdrop` directory.

What is Passphrase

![image](https://user-images.githubusercontent.com/42142420/74941314-c5fa5400-542d-11ea-8448-cbd0b6b6b6c1.png)

**Comment by tuxcanfly** [comment]
> > You need to do this from within the `hs-airdrop` directory.
> 
> What is Passphrase
> 
> ![image](https://user-images.githubusercontent.com/42142420/74941314-c5fa5400-542d-11ea-8448-cbd0b6b6b6c1.png)

That's your SSH key passphrase, if you've set one, otherwise just skip by pressing `<Enter>`

**Comment by pjmike** [comment]
> Can you try `node bin/hs-airdrop <path to key> <address> <fee>` ?

Thank you ，the solution is great .

**Comment by pinheadmz** [comment]
Thanks for your help @tuxcanfly! Going to close this for now, problem solved.

**Comment by beenotung** [comment]
Got the same error on other package (jsdu) on windows and the workaround of using `node <path-to-file>` works too.

Does that means we cannot install node.js files globally with npm?
