### ISSUE TITLE
Error: Request timed out.

### ISSUE THREAD

**Issue by zhanwen** [handshake-org/hs-airdrop#52]
![image](https://user-images.githubusercontent.com/11382789/74905459-3337c600-53e9-11ea-89c0-dcb2a86cc9e1.png)

Passphrase: If use github login, passphrase input github password?

**Comment by carsenk** [comment]
Passphrase would be your SSH or GPG key password, not your Github password.

**Comment by zhanwen** [comment]
@carsenk thanks, i try

**Comment by zhanwen** [comment]
@carsenk not true ：）

**Comment by zhanwen** [comment]
This is network problem, now i download tree.bin, i should move folder?  `node_modules\brq\`?

**Comment by carsenk** [comment]
Passphrase is definitely your SSH/GPG key. It is not your Github password.

It does seem like a network issue in your case, double check you can ping/connect to github.com

**Comment by zhanwen** [comment]
@carsenk yeah, you are right.  now i manual download tree.bin，which folder to put it in? i browse `request.js:376:19` not find path.

**Comment by YikaJ** [comment]
download `tree.bin`, and put this file into `~/.hs-tree-data`. It can solve download timeout problem.
