### ISSUE TITLE
Error: connect ECONNREFUSED 151.101.228.133:443

### ISSUE THREAD

**Issue by foolcage** [handshake-org/hs-airdrop#53]
Passphrase:
Attempting to create proof.
This may take a bit.
Decrypting nonce...
Downloading: https://github.com/handshake-org/hs-tree-data/raw/master/nonces/019.bin...
Error: connect ECONNREFUSED 151.101.228.133:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:16)

**Comment by aQuaYi** [comment]
the same with you
I just added ssh key 10 minitue ago.

**Comment by yangqihua** [comment]
run command `git clone https://gitee.com/shidenggui/hs-tree-data.git ~/.hs-tree-data`
then run `./bin/hs-airdrop path of key <address> <fee>`

**Comment by aQuaYi** [comment]
> This means your key was not found in the airdrop tree.

sad

**Comment by pinheadmz** [comment]
This error seems to be frequent and might just be a temporary issue with GitHub availability. @foolcage did this work out for you?

**Comment by foolcage** [comment]
> This error seems to be frequent and might just be a temporary issue with GitHub availability. @foolcage did this work out for you?

it's ok. I just clone the hs-tree-data directly and -d the path.

just as @yangqihua comment.
