### ISSUE TITLE
The provided claim is not valid. If you believe this is in error, please contact airdrops@namebase.io!

### ISSUE THREAD

**Issue by xiekeyi98** [handshake-org/hs-airdrop#55]
The provided claim is not valid. If you believe this is in error, please contact airdrops@namebase.io!

What can I do for this?

**Comment by xiekeyi98** [comment]
![image](https://user-images.githubusercontent.com/7782671/74907635-c293a800-53ee-11ea-894f-bf4ca5b0c789.png)

**Comment by pinheadmz** [comment]
This is not Namebase support.

**Comment by xiekeyi98** [comment]
> This is not Namebase support.

I'm very sorry for trouble this repo and file the issue with wrong way...
