### ISSUE TITLE
read ECONNRESET 

### ISSUE THREAD

**Issue by xuhaodong** [handshake-org/hs-airdrop#56]
Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:610:25)

**Comment by pinheadmz** [comment]
There is not enough context here to help you. Can you provide any more details?

**Comment by 526710585** [comment]
I had the same problem

`
Passphrase:
Attempting to create proof.
This may take a bit.
Decrypting nonce...
Downloading: https://github.com/handshake-org/hs-tree-data/raw/master/nonces/082.bin...
Error: read ECONNRESET
    at TLSWrap.onread (net.js:659:25)
`

**Comment by pinheadmz** [comment]
please see https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260
