### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by hantmac** [handshake-org/hs-airdrop#57]
When I exec `./bin/hs-airdrop ~/.ssh/id_rsa` < address> I got the error like this:

Passphrase:
Attempting to create proof.
This may take a bit.
Decrypting nonce...
Downloading: https://github.com/handshake-org/hs-tree-data/raw/master/nonces/111.bin...
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1084:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by pinheadmz** [comment]
Something just went wrong while downloading the tree data. Can you try again? If it doesn't work you can manually clone handshake-org/hs-tree-data to your home directory at `~/.hs-tree-data` and re run the script.

**Comment by hantmac** [comment]
> Something just went wrong while downloading the tree data. Can you try again? If it doesn't work you can manually clone https://github.com/handshake-org/hs-tree-data to your home directory at `~/.hs-tree-data` and re run the script.

Thanks for your reply and I have solve this problem by retrying.
