### ISSUE TITLE
errors.claimNotNamebaseAddr

### ISSUE THREAD

**Issue by fygethub** [handshake-org/hs-airdrop#58]
https://www.namebase.io says

errors.claimNotNamebaseAddr

**Comment by pinheadmz** [comment]
This is not Namebase customer support.

**Comment by jacarrichan** [comment]
address  is error.

try the  follow step:

first  .  open  this website :[ https://www.namebase.io/airdrop]
second .   click [ Click To Show Your Handshake Wallet Address]
third  .  copy  address.
