### ISSUE TITLE
Is the airdrop over?

### ISSUE THREAD

**Issue by sunbo** [handshake-org/hs-airdrop#59]

**Comment by Han-MeiM** [comment]
![image](https://user-images.githubusercontent.com/27951114/74932759-8a578e00-541d-11ea-958a-2bed605d9579.png)  
Does this mean it's over?

**Comment by pinheadmz** [comment]
Users can claim their airdrop at any time, forever. The list of qualified users is permanent and was committed just before mainnet launch. If you have any questions about anything you see on Namebase, please contact support on their website.
