### ISSUE TITLE
PEM parse error(unexpected data)

### ISSUE THREAD

**Issue by ychow** [handshake-org/hs-airdrop#61]
![image](https://user-images.githubusercontent.com/6530996/74935999-4a47d980-5424-11ea-9bd0-4f34d4c1e3f7.png)
Anyone knows how to solve this problem?

**Comment by pinheadmz** [comment]
The tool expects a private key, not a public key.

**Comment by linnbenton** [comment]
![Screenshot_48](https://user-images.githubusercontent.com/35951722/92316645-6d815180-f021-11ea-938a-ba42520fd00c.png)
after replacing a public key with a private key, then like that screenshot @pinheadmz how to solve this problem?
