### ISSUE TITLE
don't have GPG key, but have ssh key

### ISSUE THREAD

**Issue by ganler** [handshake-org/hs-airdrop#64]
this is my ssh key date
![image](https://user-images.githubusercontent.com/38074777/74970051-afb5bd80-5458-11ea-9670-1c5ca5bc7ca3.png)

this is my followers
![image](https://user-images.githubusercontent.com/38074777/74970138-d116a980-5458-11ea-9621-8030446dc492.png)

![image](https://user-images.githubusercontent.com/38074777/74970388-3f5b6c00-5459-11ea-8fe6-a80be7b219a2.png)

**Comment by pinheadmz** [comment]
What type of key is it?

https://github.com/handshake-org/hs-airdrop#accepted-key-algorithms

**Comment by NieDzejkob** [comment]
All of their keys seem to be `ssh-rsa`.

**Comment by pinheadmz** [comment]
I'm sorry your key wasn't in the airdrop tree. You can try other keys if you have them. Closing for now since this is not an issue with the code.
