### ISSUE TITLE
why,I have 19 followers

### ISSUE THREAD

**Issue by leeseean** [handshake-org/hs-airdrop#66]
.bin...
NonceError: Could not find nonce in bucket 194.
    at findNonces (C:\Users\Administrator\Desktop\hs-airdrop\bin\hs-airdrop:275:
17)
    at async createKeyProofs (C:\Users\Administrator\Desktop\hs-airdrop\bin\hs-a
irdrop:328:17)
    at async main (C:\Users\Administrator\Desktop\hs-airdrop\bin\hs-airdrop:746:
8)

This means your key was not found in the airdrop tree.
If you registered at handshake.org, use that address.
Usage: $ hs-airdrop [addr]

**Comment by pinheadmz** [comment]
https://github.com/handshake-org/hs-airdrop/issues/35#issuecomment-586699876

Maybe you didn't have followers and a valid key at the time of the snapshot.

**Comment by leeseean** [comment]
> [#35 (comment)](https://github.com/handshake-org/hs-airdrop/issues/35#issuecomment-586699876)
> 
> Maybe you didn't have followers and a valid key at the time of the snapshot.

what is the time of the snapshot?

**Comment by pinheadmz** [comment]
Feb 2019. Lots of details in the comment I linked to above.
