### ISSUE TITLE
why the base64 code is not valid

### ISSUE THREAD

**Issue by razerdp** [handshake-org/hs-airdrop#67]
I successfully generated base64, but the website prompts me that this is an incorrect code

![image](https://user-images.githubusercontent.com/11629986/75007557-7a3cbe80-54b0-11ea-8d0a-cdb9fcec2979.png)

![image](https://user-images.githubusercontent.com/11629986/75007566-8759ad80-54b0-11ea-88a7-a7fb50903699.png)

**Comment by codingWang** [comment]
Is there a solution？

**Comment by razerdp** [comment]
@codingWang  终端复制出来的base64可能带有换行，去处理掉，保证你的base64只有一行就可以了。

**Comment by codingWang** [comment]
干得漂亮
