### ISSUE TITLE
NonceError: Could not find nonce in bucket 

### ISSUE THREAD

**Issue by AbbyJM** [handshake-org/hs-airdrop#68]
I have 17followers and added my ssh key last yeaer.

**Comment by pinheadmz** [comment]
Did you have followers and a key posted by Feb 2019? That's when the snapshot was made. In addition only the most popular key algorithms were accepted. See the README.

**Comment by pinheadmz** [comment]
And see https://github.com/handshake-org/hs-airdrop/issues/35#issuecomment-586699876
