### ISSUE TITLE
When shall the key be added into my GitHub account?

### ISSUE THREAD

**Issue by BlankerL** [handshake-org/hs-airdrop#69]
As you can see, I have more than 100 followers on GitHub and most of them started following me before Feb 9, 2019. 

<img width="756" alt="image" src="https://user-images.githubusercontent.com/24969376/75008286-9f323100-54b2-11ea-8111-0f35db3afde6.png">

The image above shows that my oldest key was generated on Sep 14, 2019, and this one is not working either. 

I suppose most people will change the SSH key once a year for security reasons. Can you please tell us at what time the snapshot of our public keys was taken? 

Thank you so much.

**Comment by BlankerL** [comment]
[Here](https://github.com/handshake-org/hs-airdrop/issues/35#issuecomment-586699876) was mentioned that the public key was crawled 5 months ago. 

It is about five months from September 14, 2019, so am I just missing it?

**Comment by pinheadmz** [comment]
The snapshot is from Feb 2019. Did you have a key on GitHub at that time?

**Comment by BlankerL** [comment]
> The snapshot is from Feb 2019. Did you have a key on GitHub at that time?

Yes, but I updated and removed them almost once a year, and they are deleted from my computer. Thank you so much.
