### ISSUE TITLE
What's the meaning of argument "-f"

### ISSUE THREAD

**Issue by recolic** [handshake-org/hs-airdrop#72]
I saw an argument in `bin/hs-airdrop`:

```
-f, --fee <amount>    set fee for redemption (default: 0.1)
```

If I run `hs-airdrop ~/.gnupg/secring.gpg 0x12345678 hs1q5z7yyk8xrh4quqg3kw498ngy7hnd4sruqyxnxd -f 0.5`, will I get `4246 * 0.5 = 2123` HNS, or `4246 - 0.5 = 4245.5` HNS?

I tried `hs-airdrop ~/.gnupg/secring.gpg 0x12345678 hs1q5z7yyk8xrh4quqg3kw498ngy7hnd4sruqyxnxd -f 1.5`, and it succeeds. I broadcasted this transaction successfully, but I can not found my tx in 'hnscan.com' or 'namebase.io'. Will I receive NO HNS?

**Comment by pinheadmz** [comment]
The fee is deducted from your airdrop amount, like a Bitcoin transaction. Do not trust block explorers. In particular, hnscan dies correctly show airdrop proofs in the mempool. Miners only add ten airdrops per block and it might take a while to be confirmed. If you were able to create and send your proof without errors, you're probably fine. Just be patient.

**Comment by recolic** [comment]
> The fee is deducted from your airdrop amount, like a Bitcoin transaction. Do not trust block explorers. In particular, hnscan does not correctly show airdrop proofs in the mempool. Miners only add ten airdrops per block and it might take a while to be confirmed. If you were able to create and send your proof without errors, you're probably fine. Just be patient.

The question is, what's the meaning of -f argument... I know it's transaction fee, but I'm not sure if it's a percentage, a factor (by 1), or a immediate value.

For example, I pay 4000 HNS with argument "-f 1.5". then what's the amount of transaction fee?

**Comment by pinheadmz** [comment]
It's a flat fee expressed in HNS. Would you mind opening a PR to the README if you think you could make the experience better for future users?

**Comment by pinheadmz** [comment]
https://github.com/handshake-org/hsd/blob/f628a003a0a74b60fe794859536b04d519c06f40/lib/primitives/airdropproof.js#L276

**Comment by recolic** [comment]
> https://github.com/handshake-org/hsd/blob/f628a003a0a74b60fe794859536b04d519c06f40/lib/primitives/airdropproof.js#L276

I got it. thanks.

will open a PR soon to make it clear...
