### ISSUE TITLE
Reported scam

### ISSUE THREAD

**Issue by stomakun** [handshake-org/hs-airdrop#78]
![image](https://user-images.githubusercontent.com/4496681/75085972-c1d35100-5569-11ea-8b5d-aa9d89efb073.png)

**Comment by chjj** [comment]
Not sure where you're getting this, but you're incorrect. If software which utilizes SSH private keys for proof creation violates github's policies, then both openssh and git violate github's policies as well. If you have any evidence of a "security breach", you should post it. This issue will be closed until then (i.e. forever).

**Comment by olso** [comment]
Yup, same feeling as @stomakun
