### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by leezp** [handshake-org/hs-airdrop#79]
![image](https://user-images.githubusercontent.com/16287528/75087838-44670b00-5580-11ea-83d4-1e73598e9b4b.png)

i am using root privilege 

but canot npm install ,and there is not dir   .node-gyp .

need help

env 

![image](https://user-images.githubusercontent.com/16287528/75087863-842df280-5580-11ea-9fa1-9d73624c799c.png)

**Comment by pinheadmz** [comment]
nodejs version 10 is required at a minimum. Please upgrade node and let me know if this fixes your problem,

**Comment by archessay** [comment]
> ![image](https://user-images.githubusercontent.com/16287528/75087838-44670b00-5580-11ea-83d4-1e73598e9b4b.png)
> 
> i am using root privilege
> 
> but canot npm install ,and there is not dir .node-gyp .
> 
> need help
> 
> env
> 
> ![image](https://user-images.githubusercontent.com/16287528/75087863-842df280-5580-11ea-9fa1-9d73624c799c.png)

QQ: 631521383, I can help you.
