### ISSUE TITLE
Error: Invalid PGP key id/fingerprint.

### ISSUE THREAD

**Issue by zhuhang-jasper** [handshake-org/hs-airdrop#80]
Hi, 

I have GPG both private & public keys, but i get this error.
`Error: Invalid PGP key id/fingerprint.`

Any tips on how to export the GPG in specific way that works?
I tried:
`gpg --output public.pgp --armor --export username@email`
`gpg --output private.pgp --armor --export-secret-key username@email`
I also tried secring.gpg and the same error.

My key in git bash:
```
$ gpg --list-keys
/c/Users/zhuha/.gnupg/pubring.kbx
---------------------------------
pub   rsa4096 2018-06-18 [SC]
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
uid           [ unknown] Loo Zhu Hang (Jasper) <zhuhang.jasper@gmail.com>
sub   rsa4096 2018-06-18 [E]
```

![image](https://user-images.githubusercontent.com/3050117/75091428-12699f00-55a8-11ea-96fc-d51c22f56d8b.png)

**Comment by pinheadmz** [comment]
What command are you using for `hs-airdrop`?

From the README:

> $ hs-airdrop [key-file] [id] [addr] [options]
>   [id] is only necessary for PGP keys.
>   Examples:
>    `$ hs-airdrop ~/.gnupg/secring.gpg 0x12345678 hs1q5z7yyk8xrh4quqg3kw498ngy7hnd4sruqyxnxd -f 0.5`

**Comment by zhuhang-jasper** [comment]
(im on windows CMD, so i use node)
`node hs-airdrop C:\Users\zhuha\.gnupg\private.asc  my_address -f 0.01`
Ahhh, i missed the key ID, alright thanks for the reminder.
