### ISSUE TITLE
what is going on?

### ISSUE THREAD

**Issue by liesauer** [handshake-org/hs-airdrop#81]
so u gays just leave the issue open and lock the issue. and saying the bullshit "We have another one of these threads open here: #35", if u want us shut up, just speak it out!

**Comment by pinheadmz** [comment]
> bullshit

You are being rude. You will be banned from contributing to this organization.
Issues are not a place to complain about not qualifying for free cryptocurrency giveaways. It is only a place to report bugs or problems with the open source software the community is building.
