### ISSUE TITLE
Error: connect ETIMEDOUT 151.101.228.133:443

### ISSUE THREAD

**Issue by 526710585** [handshake-org/hs-airdrop#82]
i input code

> node bin/hs-airdrop C:/Users/Administrator/Desktop/.ssh/id_rsa hs1quycp7xfjnl2p0lyy2mrwxcskjrwd09ll59chey 0.1

then cmd  asked me Passphrase , and i I skipped it;
![Snipaste_2020-02-23_01-40-25](https://user-images.githubusercontent.com/46254079/75096773-d81af480-55dd-11ea-9afa-bdf94e57c352.png)

then:
![Snipaste_2020-02-23_01-44-53](https://user-images.githubusercontent.com/46254079/75096804-23cd9e00-55de-11ea-93f3-3b5e62836ed7.png)

What should I do??

**Comment by 526710585** [comment]
And sometimes it comes up
![Snipaste_2020-02-23_01-50-03](https://user-images.githubusercontent.com/46254079/75096868-da318300-55de-11ea-9fe3-fe16fb50513b.png)


node:10.0.0
OS:win10

**Comment by pinheadmz** [comment]
See https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260

**Comment by 526710585** [comment]
> 参见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)

Thank you very much! The page is blank after I submitted base64. I will check the balance tomorrow

**Comment by itcodes** [comment]
> > 参见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)
> 
> Thank you very much! The page is blank after I submitted base64. I will check the balance tomorrow

I have the same problem, right? Has it been solved?

**Comment by 526710585** [comment]
> > > 参见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)
> > 
> > 
> > Thank you very much! The page is blank after I submitted base64. I will check the balance tomorrow
> 
> I have the same problem, right? Has it been solved?
yes , I solved the problem. .git clone https://github.com/handshake-org/hs-tree-data to home directory at ~/.hs-tree-data and then run the script. Got the base64

**Comment by itcodes** [comment]
> > > > 见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)
> > > 
> > > 
> > > 非常感谢你！我提交base64后，该页面为空白。我明天检查余额
> > 
> > 
> > 我有同样的问题，对不对？解决了吗 
> > 是的，我解决了这个问题。.git将https://github.com/handshake-org/hs-tree-data克隆到〜/ .hs-tree-data的主目录，然后运行脚本。得到了base64

I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?

**Comment by 526710585** [comment]
> > > > > 见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)
> > > > 
> > > > 
> > > > 非常感谢你！我提交base64后，该页面为空白。我明天检查余额
> > > 
> > > 
> > > 我有同样的问题，对不对？解决了吗
> > > 是的，我解决了这个问题。.git将[https://github.com/handshake-org/hs-tree-data克隆到〜/](https://github.com/handshake-org/hs-tree-data%E5%85%8B%E9%9A%86%E5%88%B0%E3%80%9C/) .hs-tree-data的主目录，然后运行脚本。得到了base64
> 
> I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?
I have the same situation , You can rerun the script and submit the new base64 without errors. but the page is blank after I submitted the new  base64.

**Comment by 526710585** [comment]
> > > > > 见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)
> > > > 
> > > > 
> > > > 非常感谢你！我提交base64后，该页面为空白。我明天检查余额
> > > 
> > > 
> > > 我有同样的问题，对不对？解决了吗
> > > 是的，我解决了这个问题。.git将[https://github.com/handshake-org/hs-tree-data克隆到〜/](https://github.com/handshake-org/hs-tree-data%E5%85%8B%E9%9A%86%E5%88%B0%E3%80%9C/) .hs-tree-data的主目录，然后运行脚本。得到了base64
> 
> I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?
I don't know if it succeeded or failed. I used F12 in the browser and saw that the response was successful, but there was no prompt on the page. I can only check the balance tomorrow.

**Comment by itcodes** [comment]
> > > > > > 见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)
> > > > > 
> > > > > 
> > > > > 非常感谢你！我提交base64后，该页面为空白。我明天检查余额
> > > > 
> > > > 
> > > > 我有同样的问题，对不对？解决了吗
> > > > 是的，我解决了这个问题。.git将[https://github.com/handshake-org/hs-tree-data克隆到〜/](https://github.com/handshake-org/hs-tree-data%E5%85%8B%E9%9A%86%E5%88%B0%E3%80%9C/) .hs-tree-data的主目录，然后运行脚本。得到了base64
> > 
> > 
> > I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?
> > I don't know if it succeeded or failed. I used F12 in the browser and saw that the response was successful, but there was no prompt on the page. I can only check the balance tomorrow.

I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?

**Comment by 526710585** [comment]
> > > > > > > 见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)
> > > > > > 
> > > > > > 
> > > > > > 非常感谢你！我提交base64后，该页面为空白。我明天检查余额
> > > > > 
> > > > > 
> > > > > 我有同样的问题，对不对？解决了吗
> > > > > 是的，我解决了这个问题。.git将[https://github.com/handshake-org/hs-tree-data克隆到〜/](https://github.com/handshake-org/hs-tree-data%E5%85%8B%E9%9A%86%E5%88%B0%E3%80%9C/) .hs-tree-data的主目录，然后运行脚本。得到了base64
> > > 
> > > 
> > > I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?
> > > I don't know if it succeeded or failed. I used F12 in the browser and saw that the response was successful, but there was no prompt on the page. I can only check the balance tomorrow.
> 
> I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?

I just ran the script the second time and got the new base64 to submit .solved the problem. 

> Errors.claimnotnamebaseaddr

**Comment by itcodes** [comment]
> > > > > > > > 见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)
> > > > > > > 
> > > > > > > 
> > > > > > > 非常感谢你！我提交base64后，该页面为空白。我明天检查余额
> > > > > > 
> > > > > > 
> > > > > > 我有同样的问题，对不对？解决了吗
> > > > > > 是的，我解决了这个问题。.git将[https://github.com/handshake-org/hs-tree-data克隆到〜/](https://github.com/handshake-org/hs-tree-data%E5%85%8B%E9%9A%86%E5%88%B0%E3%80%9C/) .hs-tree-data的主目录，然后运行脚本。得到了base64
> > > > 
> > > > 
> > > > I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?
> > > > I don't know if it succeeded or failed. I used F12 in the browser and saw that the response was successful, but there was no prompt on the page. I can only check the balance tomorrow.
> > 
> > 
> > I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?
> 
> I just ran the script the second time and got the new base64 to submit .solved the problem.
> 
> > Errors.claimnotnamebaseaddr

According to your method, I have just successfully solved the problem

**Comment by itcodes** [comment]
> > > > > > > > 见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)
> > > > > > > 
> > > > > > > 
> > > > > > > 非常感谢你！我提交base64后，该页面为空白。我明天检查余额
> > > > > > 
> > > > > > 
> > > > > > 我有同样的问题，对不对？解决了吗
> > > > > > 是的，我解决了这个问题。.git将[https://github.com/handshake-org/hs-tree-data克隆到〜/](https://github.com/handshake-org/hs-tree-data%E5%85%8B%E9%9A%86%E5%88%B0%E3%80%9C/) .hs-tree-data的主目录，然后运行脚本。得到了base64
> > > > 
> > > > 
> > > > I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?
> > > > I don't know if it succeeded or failed. I used F12 in the browser and saw that the response was successful, but there was no prompt on the page. I can only check the balance tomorrow.
> > 
> > 
> > I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?
> 
> I just ran the script the second time and got the new base64 to submit .solved the problem.
> 
> > Errors.claimnotnamebaseaddr

你的币到了吗？为啥我的一直在pending

**Comment by 526710585** [comment]
> > > > > > > > > 见[＃57（评论）](https://github.com/handshake-org/hs-airdrop/issues/57#issuecomment-588994260)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 非常感谢你！我提交base64后，该页面为空白。我明天检查余额
> > > > > > > 
> > > > > > > 
> > > > > > > 我有同样的问题，对不对？解决了吗
> > > > > > > 是的，我解决了这个问题。.git将[https://github.com/handshake-org/hs-tree-data克隆到〜/](https://github.com/handshake-org/hs-tree-data%E5%85%8B%E9%9A%86%E5%88%B0%E3%80%9C/) .hs-tree-data的主目录，然后运行脚本。得到了base64
> > > > > 
> > > > > 
> > > > > I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?
> > > > > I don't know if it succeeded or failed. I used F12 in the browser and saw that the response was successful, but there was no prompt on the page. I can only check the balance tomorrow.
> > > 
> > > 
> > > I submitted a base64 shows: errors. ClaimNotNamebaseAddr. Don't know why?
> > 
> > 
> > I just ran the script the second time and got the new base64 to submit .solved the problem.
> > > Errors.claimnotnamebaseaddr
> 
> Have you got your money? Why is my pending all the time

I got it,maybe you should wait a while

**Comment by itcodes** [comment]
> I got it,maybe you should wait a while

Did you get it?
