### ISSUE TITLE
Error using exported gpg key

### ISSUE THREAD

**Issue by mewwts** [handshake-org/hs-airdrop#94]
Hey devs,

I'm getting the following error when running
```
→ ./bin/hs-airdrop private.gpg xxxx 0.010  
Error: Invalid PGP key id/fingerprint.
    at Object.decodeID (/home/mats/dev/handshake/hs-airdrop/node_modules/bcrypto/
    at parseArgs (/home/mats/dev/handshake/hs-airdrop/bin/hs-airdrop:700:25)     
    at main (/home/mats/dev/handshake/hs-airdrop/bin/hs-airdrop:740:25)
    at Object.<anonymous> (/home/mats/dev/handshake/hs-airdrop/bin/hs-airdrop:803
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)     
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
```
having exported my github-associated pgp-key using 

```
gpg --output private.gpg --armor --export-secret-key yyyyyy
```
where `yyyyy` is my key id. 

I remember having logged into handshake.org previosuly, so I also wonder if I were deduped in some way - and I've stored privately and _two_ seeds. Is there any way to log in to hanshake.org to verify?

Or how do I detect if the coins were dropped to an address in the seed?

**Comment by boymanjor** [comment]
@mewwts if you signed up on handshake.org, your key was removed from the airdrop tree. You will be able to claim your portion of the faucet using the address you registered on the website. You can verify this by searching for your faucet address in this [file](https://github.com/handshake-org/hs-tree-data/blob/master/proof.json).

However, the above error does _not_ imply your key is not in the airdrop tree. I see a couple of issues with your reported commands.

1. You are missing an argument in your airdrop command. I'm not sure if `xxxx` refers to your gpg key id or HNS address, but both are required. The error makes be believe you are only passing in your HNS address. Run `hs-airdrop -h` to view the usage instructions.

2. You have instructed `gpg` to export your key in ascii, but the `.gpg` file extension implies binary data. Either rename `private.gpg` to `private.asc` or export your key without the `--armor` flag.

**Comment by mewwts** [comment]
Got it. 

Thank you @boymanjor. I now tried renaming the key and then the process failed with the expected `NonceError`. I think it's clear that my keys have been deduped since I signed up on handshake.org. I'm struggling to figure out how I can log back in to handshake.org to find my info - any pointers?

**Comment by boymanjor** [comment]
The handshake.org faucet site has been shut down. I do not think there is any way to log into that site. @hschoenburg any insight here?

However, if you have your seed phrase, you will be able to generate the faucet address by importing the phrase into a Handshake wallet. You can use [hsd](https://github.com/handshake-org/hsd) or [Bob](https://github.com/kyokan/bob-wallet).

At this point, I think all faucet claims have already been mined. The faucet claims did not require signatures from the recipients and included sizeable fees to incentivize early block inclusion by miners. This made it advantageous for miners submit the faucet claims themselves, to collect the fees. My guess is once you import your seed phrase into a wallet, you will have an HNS balance waiting for you.

**Comment by mewwts** [comment]
Got it thanks! 

I realise this is getting off topic for `hs-airdrop`, please just let me know where I should move this discussion if there are better venues: after importing seed-phrases using `mkwallet` in `hsw-cli`, should I see the balance immediately without creating any addresses? Or would I have to generate an account first?

**Comment by mewwts** [comment]
Nevermind, found the coins on the default address of the seed. The issue was my local node apparently not being synced. Thanks for your help @boymanjor .
